# Generated by Django 3.0.8 on 2020-07-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=1, max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
    ]
