# Generated by Django 3.0.8 on 2020-08-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
