# Generated by Django 3.0.8 on 2020-08-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20200830_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='s_address',
        ),
    ]
