# Generated by Django 3.0.8 on 2020-09-01 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_auto_20200901_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
    ]
