# Generated by Django 3.0.8 on 2020-09-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_auto_20200901_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
