# Generated by Django 3.0.8 on 2020-09-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0043_auto_20200901_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
