# Generated by Django 3.0.8 on 2020-09-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_testorder_testorderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='testorderproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
    ]
