# Generated by Django 3.0.8 on 2020-09-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0046_testorderproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='user',
        ),
        migrations.AddField(
            model_name='testorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product'),
        ),
        migrations.DeleteModel(
            name='TestOrderProduct',
        ),
    ]
