# Generated by Django 3.0.8 on 2020-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0048_auto_20200902_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testorder',
            name='products',
        ),
        migrations.AddField(
            model_name='testorder',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
