# Generated by Django 3.0.8 on 2020-09-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0052_auto_20200914_1857'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
