# Generated by Django 3.0.8 on 2020-09-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0053_auto_20200915_1103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
