# Generated by Django 3.0.8 on 2020-11-10 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0055_auto_20201110_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='store',
            new_name='storeNo',
        ),
    ]
