# Generated by Django 3.0.8 on 2020-11-10 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0056_auto_20201110_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
